version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: web-store-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: web-store-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: webstore@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "42080:80"
    networks:
      - pg-network

  app:
    build: .
    container_name: web-store-app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3400:3400"
    environment:
      DB_HOST: "web-store-postgres"
      DB_NAME: "webstore"
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_PORT: 5432
      PORT: 3400
    depends_on:
      - postgres
    command: npm run start
    networks:
      - pg-network

  frontend:
    build:
      context: /Users/kimmeir/Documents/Projects/angular/andrewStore
      dockerfile: Dockerfile
    container_name: web-store-frontend
    restart: always
    volumes:
      - /Users/kimmeir/Documents/Projects/angular/andrewStore/dist/andrew-store/browser
    ports:
      - "4500:80"
    networks:
      - pg-network

volumes:
  postgres_data:

networks:
  pg-network:
